---
- name: Include the tasks for setting up the server
  become: yes
  include_role:
    name: minecraft-server
    tasks_from: install-java

- name: Include the tasks for setting up the server
  become: yes
  include_role:
    name: minecraft-server
    tasks_from: start-valheim-server